version: '3.8'

services:
  php-app:
    image: php:8.2-apache
    container_name: php-app
    ports:
      - "8081:80"
    volumes:
      - ./php-app:/var/www/html

  node-app:
    image: node:20
    container_name: node-app
    working_dir: /app
    volumes:
      - ./node-app:/app
    command: ["node", "server.js"]
    ports:
      - "8082:3000"

  java-app:
    build:
      context: ./java-app
    container_name: java-app
    ports:
      - "8083:8080"

  nginx-lb:
    image: nginx
    container_name: nginx-lb
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
